server:
  port: 8083
spring:
  application:
    name: zx_Logservice

  datasource:
    url: jdbc:clickhouse://${zxzy.clickhouse.host}:${zxzy.clickhouse.port:8123}/${zxzy.clickhouse.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username: ${zxzy.clickhouse.user}
    password: ${zxzy.clickhouse.pw}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
#      id-type: auto
seata:
  registry:
    type: file
  enabled: false # 是否启用 Seata
  application-id: ${spring.application.name} # Seata 应用 ID，通常与 Spring 应用名一致
  tx-service-group: default # 事务服务组名，需与 Seata Server 端配置一致

  client:
    rm:
      mode: "AT" # 事务模式，AT 模式是默认和最常用的
      transaction-table-name: "undo_log" # AT 模式下业务库中的 undo_log 表名
    tm:
      commit-retry-count: 5 # TM 提交事务的重试次数
      rollback-retry-count: 5 # TM 回滚事务的重试次数

  service:
    # 核心配置：直接指定 Seata Server 地址列表
    grouplist:
      default_tx_group: 113.45.186.208:8091 # 替换为你的 Seata Server 实际 IP 和端口
      # 如果有多个 Seata Server 实例组成集群，可以像这样用逗号分隔
      # default_tx_group: 192.168.1.100:8091,192.168.1.101:8091
zxzy:
  clickhouse:
    host: 113.45.186.208
    port: 8123
    user: root
    pw: zx_service_homework_l2yz
    database: http_log_db

#logging:
#  level:
#    org.zalando.logbook: INFO # 设置 Logbook 的日志级别

#logbook:
#  sink:
#    type: file
#    file:
#      directory: ./logs # 指定日志文件存储目录
#      filename-pattern: http-%d{yyyy-MM-dd}.json # 配置日志文件名模式，按天生成 JSON 文件
#  format:
#    style: json # 设置日志输出格式为 JSON
